/* Lucent — Data
   Single source of truth for services, cases, process steps, industries, FAQs.
   Exported to window so any page-script can read it. */

const LUCENT_SERVICES = [
  {
    slug: "custom-software",
    n: "01",
    short: "Custom Software",
    title: "Custom Software Development",
    titleEm: "Maßgeschneidert.",
    eyebrow: "INDIVIDUELLE SOFTWARE",
    tagline: "Anwendungen, die genau das tun, was euer Geschäft braucht — und nichts, was es nicht braucht.",
    problem: "Standard-Software bremst euch aus. Ihr klebt mit Excel-Tabellen, Workarounds und manuellen Übergaben zusammen, was eigentlich ein Klick sein sollte.",
    builds: "Wir bauen Web-Apps, interne Tools und Backends, die euer Team täglich benutzt. Sauber dokumentiert, getestet, deploybar — keine Black Boxes.",
    examples: [
      { label: "ERWEITERTES CRM", title: "CRM mit Vertriebs-Logik", desc: "Ein CRM, das den realen Sales-Prozess abbildet — inkl. Lead-Scoring, Provisionsabrechnung und Kalender-Sync." },
      { label: "INTERNES TOOL", title: "Auftragsverwaltung mit Echtzeitstatus", desc: "Aufträge, Disposition und Lagerstand in einer Oberfläche — statt drei getrennten Tabs und einem WhatsApp-Chat." },
      { label: "B2B-PORTAL", title: "Selfservice-Portal für Geschäftskunden", desc: "Kunden sehen offene Rechnungen, laden Belege hoch, melden Tickets — euer Support hat 40% weniger Anrufe." },
    ],
    features: [
      { n: "01", t: "Architektur, die mitwächst", d: "Klares Domain-Modell, modulare Services, automatisierte Tests. Heute MVP, in zwei Jahren tragfähige Plattform." },
      { n: "02", t: "Echte Software statt Workflow-Tool", d: "Wir bauen mit TypeScript, Node/Go, Postgres — kein Drag-and-Drop-Tool, das nach zwei Jahren stirbt." },
      { n: "03", t: "Wöchentliche Demos auf eurer Staging-Umgebung", d: "Ihr seht, woran wir arbeiten — nicht nur Tickets in Jira. Feature-Flags, sodass ihr selbst entscheidet, wann etwas live geht." },
      { n: "04", t: "Code, der euch gehört", d: "Repository in eurer Organisation, vollständige Dokumentation, Onboarding-Sessions für euer Team. Kein Lock-in." },
    ],
    deliverables: [
      "Funktionierende Anwendung in produktivem Einsatz",
      "Saubere Test-Coverage (Unit, Integration, E2E)",
      "CI/CD-Pipeline mit automatischen Deployments",
      "Technische Dokumentation und Architektur-Diagramm",
      "Runbook für Betrieb und Wartung",
      "Onboarding-Sessions für euer Team",
    ],
    tags: ["Web-Apps", "SaaS", "Backend", "TypeScript", "Postgres", "REST", "GraphQL"],
    meta: { duration: "8–16 Wochen", team: "2–4 Senior", budget: "ab 35k €", phase: "Discovery → Launch" },
    cta: "Lasst uns euer Tool bauen",
    vizKind: "engineering",
  },
  {
    slug: "ai-automation",
    n: "02",
    short: "AI & Automation",
    title: "KI & Automatisierung",
    titleEm: "im Produktiveinsatz.",
    eyebrow: "APPLIED AI",
    tagline: "KI-Integration in echte Workflows — mit Quellen, Auswertung und Kontrolle. Keine Pilot-Projekte, die nie skalieren.",
    problem: "Eure Mitarbeiter:innen verbringen Stunden mit Aufgaben, die ein LLM in Sekunden erledigen könnte — wenn man weiß, wo die Grenzen sind und wie man Halluzinationen verhindert.",
    builds: "RAG-Systeme, KI-Agenten, klassische Klassifizierer und automatisierte Workflows. Mit Evaluierung, Logging und einem klaren Kostenmodell.",
    examples: [
      { label: "LEAD QUALIFIZIERUNG", title: "Automatisches Lead-Scoring", desc: "Eingehende Anfragen werden klassifiziert, mit CRM-Daten angereichert und nach Passgenauigkeit sortiert — bevor Sales sie überhaupt sieht." },
      { label: "DOKUMENTEN-OCR", title: "Rechnungen, Verträge, Lieferscheine extrahieren", desc: "Unstrukturierte PDFs werden zu strukturierten Datensätzen. Mit Validierung und menschlicher Freigabe an den richtigen Stellen." },
      { label: "WISSENS-RAG", title: "Interne Wissensdatenbank durchsuchbar machen", desc: "Mitarbeiter:innen fragen in natürlicher Sprache; das System antwortet mit Quellenangaben aus euren Dokumenten — keine Halluzination." },
    ],
    features: [
      { n: "01", t: "Quellen statt Halluzinationen", d: "Jede KI-Antwort enthält Verweise. Wenn das Modell unsicher ist, sagt es das — und eskaliert an einen Menschen." },
      { n: "02", t: "Evaluierung von Tag eins", d: "Wir bauen ein Eval-Set mit euren echten Beispielen, bevor wir Modell oder Prompt anfassen. Damit messbar bleibt, was wir tun." },
      { n: "03", t: "Kostenmodell, das nicht explodiert", d: "Caching, Smart-Routing zwischen Modellen, Batch-Verarbeitung wo möglich. Wir zeigen euch monatlich, was die KI kostet — pro Use Case." },
      { n: "04", t: "Mensch im Loop, wo es zählt", d: "Hohe Confidence → automatisch. Niedrige Confidence → Mensch entscheidet. Klare Schwellen, kein 'die KI hat das so entschieden'." },
    ],
    deliverables: [
      "Funktionsfähiger AI-Workflow im produktiven Einsatz",
      "Evaluations-Set mit Benchmark-Werten",
      "Logging und Cost-Dashboard pro Use Case",
      "Fallback-Logik bei Modell-Ausfällen",
      "Promp-Templates und Modell-Konfigurationen versioniert",
      "Datenschutz- und DSGVO-Konzept (kein Trainingsdaten-Leak)",
    ],
    tags: ["LLMs", "RAG", "Eval", "Vector DB", "OpenAI", "Anthropic", "OCR"],
    meta: { duration: "6–14 Wochen", team: "2–3 Senior", budget: "ab 28k €", phase: "Eval → Pilot → Roll-out" },
    cta: "KI-Projekt prüfen lassen",
    vizKind: "ai",
  },
  {
    slug: "system-integrations",
    n: "03",
    short: "System-Integrationen",
    title: "System-Integrationen",
    titleEm: "ohne Kabelsalat.",
    eyebrow: "API & INTEGRATION",
    tagline: "CRM mit ERP, Shop mit Buchhaltung, Tool A mit Tool B — wir verbinden eure Systeme, sodass Daten fließen statt liegen.",
    problem: "Eure Systeme reden nicht miteinander. Daten werden manuell übertragen, Fehler schleichen sich ein, niemand weiß, wo die Wahrheit ist.",
    builds: "Sauber dokumentierte APIs, robuste Integrationen mit Retry- und Fehler-Logik, Webhook-Endpoints und Daten-Mappings — mit Monitoring und einer klaren Single Source of Truth.",
    examples: [
      { label: "ERP × SHOP", title: "Shopify ↔ SAP-Anbindung", desc: "Bestellungen, Bestände, Kundendaten in Echtzeit synchron — ohne CSV-Imports zur Mitternacht." },
      { label: "CRM × BILLING", title: "HubSpot ↔ Stripe ↔ DATEV", desc: "Vom Sales-Abschluss bis zur Buchung in DATEV automatisch. Vertragsabschluss → Rechnung → Mahnwesen → Verbuchung." },
      { label: "WEBHOOKS", title: "Event-Bus zwischen 12 Systemen", desc: "Statt 12×12 Punkt-zu-Punkt-Integrationen ein zentraler Event-Bus. Skalierbar, observable, fehlertolerant." },
    ],
    features: [
      { n: "01", t: "Idempotente Endpunkte", d: "Doppelte Webhooks, Retries, Race-Conditions — Standardfälle, die wir von Anfang an einplanen." },
      { n: "02", t: "Datenfluss-Diagramm vor der Tastatur", d: "Wir mappen erst, wo welche Daten herkommen, wer sie ändert, wer sie braucht. Dann bauen wir." },
      { n: "03", t: "Monitoring und Alerts", d: "Jeder Integrations-Punkt hat Metriken: Latenz, Fehlerrate, Backlog. Bei Problemen wisst ihr es vor euren Kunden." },
      { n: "04", t: "Datenschutz und Audit-Trail", d: "Wer hat wann was übertragen? Jeder Datenfluss ist auditierbar — wichtig für DSGVO, ISO und interne Compliance." },
    ],
    deliverables: [
      "Integrations-Service mit dokumentierten Endpunkten",
      "Datenfluss- und Sequenz-Diagramme",
      "Monitoring-Dashboard mit Alerts",
      "Retry- und Dead-Letter-Queue für Fehlerfälle",
      "OpenAPI-Spec für eigene Endpunkte",
      "Übergabe- und Betriebs-Dokumentation",
    ],
    tags: ["REST", "GraphQL", "Webhooks", "Kafka", "Postgres", "OpenAPI", "OAuth"],
    meta: { duration: "4–10 Wochen", team: "2 Senior", budget: "ab 22k €", phase: "Mapping → Build → Cutover" },
    cta: "Integrations-Skizze anfragen",
    vizKind: "integration",
  },
  {
    slug: "dashboards",
    n: "04",
    short: "Dashboards & Data",
    title: "Dashboards & Daten-Produkte",
    titleEm: "Entscheidungen messbar.",
    eyebrow: "DATEN & ANALYTICS",
    tagline: "Echte Dashboards mit echten Daten — kein BI-Tool, in dem niemand sich auskennt, sondern eine Oberfläche, die euer Team versteht.",
    problem: "Die Daten liegen verteilt in fünf Systemen, das Dashboard im BI-Tool kann niemand bedienen, und am Ende entscheidet das Bauchgefühl.",
    builds: "Wir bauen interne Dashboards und Reporting-Tools, die auf eure Daten zugreifen, sie in Echtzeit aufbereiten und genau die Fragen beantworten, die ihr stellt.",
    examples: [
      { label: "OPS-DASHBOARD", title: "Live-Übersicht für die Geschäftsleitung", desc: "Umsatz, Pipeline, Lagerstand, offene Tickets — auf einem Bildschirm, jeden Morgen aktuell, mit Drill-Down." },
      { label: "MARKETING-ATTRIBUTION", title: "Kanalattribution ohne Glaubenskrieg", desc: "Welche Kampagne hat den Umsatz gebracht? Multi-Touch-Attribution mit transparenter Logik — kein Black-Box-Tool." },
      { label: "INTERNE METRIKEN", title: "Produkt- und Engineering-KPIs", desc: "DORA-Metriken, Feature-Adoption, Funnel-Drop-offs — was euer Produktteam jede Woche braucht." },
    ],
    features: [
      { n: "01", t: "Eine Quelle der Wahrheit", d: "ETL-Pipelines, die saubere, validierte Daten in ein Warehouse schreiben. Alle Dashboards lesen von dort." },
      { n: "02", t: "Schnell, weil pre-computed", d: "Wir berechnen aggregierte Werte vor — Dashboards laden in Millisekunden, auch wenn dahinter 50 Mio. Zeilen liegen." },
      { n: "03", t: "Ad-hoc-Fragen mit SQL-Layer", d: "Für Power-User: direkter SQL-Zugriff aufs Warehouse. Für alle anderen: kuratierte Dashboards mit klaren Filtern." },
      { n: "04", t: "Versionierte Reports", d: "Jeder Report ist Code im Git. Änderungen werden reviewed, deployed und sind nachvollziehbar — keine 'wer hat die Kennzahl geändert?'-Diskussion." },
    ],
    deliverables: [
      "Data-Warehouse mit dokumentierten Tabellen",
      "ETL/ELT-Pipelines mit Monitoring",
      "Dashboard-Anwendung mit rollenbasierter Sicht",
      "Daten-Wörterbuch und KPI-Definitionen",
      "SQL-Layer für Ad-hoc-Analysen",
      "Schulung für Daten-Verantwortliche",
    ],
    tags: ["Postgres", "ClickHouse", "dbt", "Metabase", "Looker", "Python", "Airflow"],
    meta: { duration: "6–12 Wochen", team: "2 Senior", budget: "ab 26k €", phase: "Modelling → ETL → UI" },
    cta: "Dashboard-Konzept besprechen",
    vizKind: "data",
  },
  {
    slug: "ux-ui",
    n: "05",
    short: "UX/UI & Product Design",
    title: "UX/UI & Product Design",
    titleEm: "Design, das funktioniert.",
    eyebrow: "DESIGN & PROTOTYPING",
    tagline: "Vom Wireframe zur finalen UI — mit Design-System, das euer Entwicklungs-Team auch wirklich verwendet.",
    problem: "Designs in Figma sehen schön aus, aber im fertigen Produkt sieht jeder Screen anders aus. Buttons haben fünf Größen, Farben heißen unterschiedlich, niemand weiß, was die kanonische Variante ist.",
    builds: "Wir bauen Design-Systeme mit Tokens, Komponenten-Bibliothek in eurer Codebase und klaren Regeln, die Designer und Entwickler:innen gemeinsam pflegen.",
    examples: [
      { label: "PRODUKT-REDESIGN", title: "Bestehendes SaaS-Produkt neu denken", desc: "Bestehende Funktionen, neue Informationsarchitektur. Mit klaren A/B-Tests, statt Annahmen." },
      { label: "DESIGN SYSTEM", title: "Tokens + React-Component-Library", desc: "Farben, Typografie, Spacings als Tokens. Buttons, Inputs, Karten als React-Komponenten. Storybook + Tests inklusive." },
      { label: "WIREFRAME → UI", title: "Interaktiver Prototyp aus Wireframes", desc: "Vom Skizzen-Wireframe in Figma zu einem klickbaren Prototyp mit echtem Verhalten — vor dem Engineering-Sprint." },
    ],
    features: [
      { n: "01", t: "Design-Tokens als Single Source", d: "Farben, Spacings, Schatten in einer JSON-Datei — verwendet von Figma UND eurer Codebase. Geändert hier, geändert überall." },
      { n: "02", t: "Komponenten in eurer Codebase", d: "Wir bauen Komponenten direkt in eurem React/Vue/Svelte-Setup. Mit Storybook, Tests, Accessibility-Checks — kein Figma-Mockup, das nie produktionsreif wird." },
      { n: "03", t: "Accessibility ist Default", d: "WCAG AA, Tastatur-Navigation, Screenreader-Tests. Nicht als Nachgedanke, sondern in jeder Komponente." },
      { n: "04", t: "Übergabe ohne Reibungsverlust", d: "Designer und Entwickler:innen arbeiten am selben Token-Set. Spec-Sheets entfallen — die Spec IST der Code." },
    ],
    deliverables: [
      "Design-Tokens als JSON + Figma-Variables",
      "Komponenten-Library in eurer Codebase",
      "Storybook mit Beispielen und Dokumentation",
      "Accessibility-Audit und WCAG-Konformität",
      "Onboarding-Doku für Design + Engineering",
      "Roadmap zur Pflege und Weiterentwicklung",
    ],
    tags: ["Figma", "Tokens", "Storybook", "React", "A11y", "Design Ops"],
    meta: { duration: "4–10 Wochen", team: "1 Designer + 1 Dev", budget: "ab 18k €", phase: "Audit → System → Build" },
    cta: "Design-Review buchen",
    vizKind: "design",
  },
  {
    slug: "web-platforms",
    n: "06",
    short: "Web-Plattformen",
    title: "Web-Plattformen",
    titleEm: "performant. skalierbar.",
    eyebrow: "WEB & PERFORMANCE",
    tagline: "Public-facing Web-Plattformen, Marketplaces und Portale — schnell, SEO-stark, ohne Wartungs-Albträume.",
    problem: "Eure Website lädt in 4 Sekunden, das CMS ist eine Bastelei, das Marketing-Team wagt nichts mehr zu ändern, und Google straft euch ab.",
    builds: "Wir bauen Web-Plattformen mit Next.js, headless CMS und einer Editor-Erfahrung, die euer Marketing-Team alleine pflegen kann — ohne Tickets ans Engineering.",
    examples: [
      { label: "MARKETPLACE", title: "Mehrseitiger Marktplatz mit Custom-Suche", desc: "Anbieter, Käufer, Suche, Zahlungsabwicklung — als eigenständige Plattform. SEO-stark, skaliert auf Millionen Visits." },
      { label: "B2B-PORTAL", title: "Kundenportal mit Self-Service", desc: "Login, Verträge, Rechnungen, Tickets — als gebrandetes Portal mit SSO und granularen Rechten." },
      { label: "CONTENT-WEBSITE", title: "Marketing-Site mit echtem CMS", desc: "Headless CMS (Sanity/Contentful), Marketing-Team pflegt Inhalte selbst, Performance bleibt unter 1.5s LCP." },
    ],
    features: [
      { n: "01", t: "Core Web Vitals als Akzeptanz-Kriterium", d: "LCP unter 1.5s, INP unter 200ms, CLS unter 0.1 — gemessen, nicht behauptet. Vor jedem Deploy." },
      { n: "02", t: "Editor-Erfahrung, die euer Team mag", d: "Inline-Editing, Preview-Mode, Branch-Workflows — kein 1990er-CMS, in dem niemand mehr eine Seite anfasst." },
      { n: "03", t: "SEO ist Architektur, nicht Plug-in", d: "Server-Rendering, saubere URL-Struktur, strukturierte Daten, Sitemaps automatisch. Google sieht, was Nutzer:innen sehen." },
      { n: "04", t: "Auf Edge geliefert, weltweit", d: "CDN, Edge-Functions, regionale Caching-Strategie. Eure Plattform fühlt sich in Sydney genauso schnell an wie in Stuttgart." },
    ],
    deliverables: [
      "Produktive Web-Plattform mit CI/CD",
      "Headless-CMS-Setup und Redaktions-Doku",
      "Core-Web-Vitals-Budget und Monitoring",
      "SEO-Setup (Sitemaps, Schema, Redirects)",
      "Mehrsprachigkeit und i18n-Architektur",
      "Übergabe an Marketing- und Tech-Team",
    ],
    tags: ["Next.js", "Sanity", "Contentful", "Vercel", "Edge", "i18n", "Schema.org"],
    meta: { duration: "6–14 Wochen", team: "2–3 Senior", budget: "ab 30k €", phase: "Architecture → Build → Launch" },
    cta: "Plattform-Skizze besprechen",
    vizKind: "platform",
  },
];

const LUCENT_CASES = [
  {
    slug: "ai-lead-qualification",
    tag: "AI · 2025",
    title: "KI-Lead-Qualifizierung für ein B2B-Sales-Team",
    short: "150 eingehende Anfragen pro Woche — KI bewertet und reichert sie an, bevor Sales sie sieht.",
    industry: "B2B-Sales",
    duration: "9 Wochen",
    role: "Discovery → Build → Roll-out",
    stack: ["TypeScript", "Node.js", "Postgres", "OpenAI", "HubSpot API", "Webhooks"],
    relatedService: "ai-automation",
    problem: "Ein B2B-Software-Anbieter erhielt 150 eingehende Anfragen pro Woche. Drei Personen im Inside-Sales-Team verbrachten den halben Tag damit, Anfragen zu lesen, im Web nach Firmen-Infos zu suchen, ins CRM einzutragen und zu priorisieren. Die guten Leads gingen im Rauschen unter — Reaktionszeit auf hochwertige Anfragen lag bei 14 Stunden.",
    solution: "Eingehende Formular-Anfragen laufen über einen Webhook in eine Klassifizierungs-Pipeline. Ein LLM extrahiert Firma, Rolle, Branche und Anliegen. Eine zweite Pipeline reichert mit öffentlichen Daten an (Firmensitz, Größe, Branche). Ein klassisches Modell bewertet auf Basis historischer Conversion-Daten. Hoch bewertete Leads landen sofort als Aufgabe im CRM mit Slack-Notification; niedrig bewertete in einer Nurture-Sequenz.",
    workflow: [
      { icon: "✉", t: "Eingang", d: "Formular oder Email" },
      { icon: "⤴", t: "Extraktion", d: "LLM strukturiert" },
      { icon: "⟲", t: "Anreicherung", d: "Public Data API" },
      { icon: "★", t: "Scoring", d: "Modell + Regeln" },
      { icon: "→", t: "CRM", d: "HubSpot + Slack" },
    ],
    components: [
      "Webhook-Empfänger für Formular- und Mail-Eingänge",
      "LLM-Extraktion mit strukturiertem JSON-Output",
      "Anreicherungs-Service mit Caching gegen externe APIs",
      "Scoring-Modell, trainiert auf 18 Monaten Conversion-Daten",
      "CRM-Integration mit Aufgaben, Tags und Notes",
      "Slack-Notifications für Tier-A-Leads",
      "Admin-Oberfläche zur Korrektur und Feedback-Loop",
    ],
    result: "Reaktionszeit auf Tier-A-Leads sank von 14 Stunden auf unter 20 Minuten. Inside-Sales-Team wendet 70% weniger Zeit auf Qualifizierung auf und kann sich auf Erstgespräche konzentrieren. Conversion-Rate Tier-A → Erstgespräch stieg um 38%.",
    metrics: [
      { val: "−96%", lab: "Reaktionszeit Tier-A", note: "14h → 20min" },
      { val: "−70%", lab: "Qualifizierungs-Aufwand", note: "Stunden pro Woche" },
      { val: "+38%", lab: "Conversion zu Erstgespräch", note: "über 3 Monate" },
      { val: "150/Wo", lab: "Anfragen automatisiert", note: "0 manuell" },
    ],
    vizKind: "ai",
  },
  {
    slug: "internal-dashboard",
    tag: "B2B · 2024",
    title: "Operations-Dashboard für ein Logistik-Unternehmen",
    short: "Vier Excel-Tabellen, drei Tools, eine WhatsApp-Gruppe — ersetzt durch ein internes Tool.",
    industry: "Logistik",
    duration: "12 Wochen",
    role: "Discovery → Build → Übergabe",
    stack: ["TypeScript", "Next.js", "Postgres", "Redis", "Mapbox", "WebSockets"],
    relatedService: "dashboards",
    problem: "Ein Logistik-Unternehmen mit 80 Mitarbeiter:innen koordinierte tägliche Touren über vier Excel-Tabellen, ein altes Disponenten-Tool und eine WhatsApp-Gruppe. Disponentinnen wussten nicht, ob eine Tour aktuell läuft, im Stau steht oder fertig ist. Kunden riefen an, weil keine ETAs verfügbar waren. Wochenende-Bereitschaft war ein Albtraum.",
    solution: "Wir bauten ein internes Ops-Dashboard mit drei Sichten: Disposition (Touren-Planung mit Drag-and-Drop), Live-Map (alle Fahrzeuge in Echtzeit, ETAs), und Kunden-Cockpit (Auftragsstatus, Verlauf, Tracking-Links). Datenquellen wurden konsolidiert: Telematik-API, Auftragsverwaltung, Kunden-Portal. Auf der Map sieht die Disponentin auf einen Blick, welche Tour läuft, welche fertig ist, wo gerade ein Problem ist.",
    workflow: [
      { icon: "▤", t: "Disposition", d: "Drag-and-Drop" },
      { icon: "⌖", t: "Telematik", d: "Live-Position" },
      { icon: "↗", t: "ETA-Service", d: "Routing + Verkehr" },
      { icon: "✉", t: "Kunden-Mail", d: "Auto-ETA" },
      { icon: "▣", t: "Dashboard", d: "Ops + Mgmt-View" },
    ],
    components: [
      "Datenkonsolidierung aus Telematik-, ERP- und Kunden-System",
      "Live-Map mit Mapbox und WebSocket-Updates",
      "Drag-and-Drop-Tour-Planung",
      "ETA-Engine mit Verkehrsdaten",
      "Kunden-Tracking-Links per E-Mail",
      "Rollen-basierte Sichten (Disposition, Fahrer, Management)",
      "Mobile-App-Modus für Fahrer:innen",
    ],
    result: "Anrufe von Kunden zu ETAs gingen um 64% zurück. Disponent:innen sparen pro Schicht rund 90 Minuten Routine-Arbeit. Wochenendbereitschaft kann von einer Person übernommen werden — vorher waren zwei nötig. Excel-Tabellen wurden abgeschaltet.",
    metrics: [
      { val: "−64%", lab: "Kundenanrufe zu ETAs", note: "über 4 Monate" },
      { val: "+90min", lab: "Zeit gespart pro Schicht", note: "pro Disponent" },
      { val: "−50%", lab: "Wochenend-Bereitschaft", note: "2 → 1 Person" },
      { val: "0", lab: "Excel-Tabellen", note: "vorher: 4" },
    ],
    vizKind: "dashboard",
  },
  {
    slug: "customer-portal",
    tag: "FINTECH · 2025",
    title: "Selfservice-Kundenportal für einen Versicherer",
    short: "Schadenmeldung, Dokumente, Status — als Portal, das auch Großeltern bedienen können.",
    industry: "Fintech / Versicherung",
    duration: "16 Wochen",
    role: "Discovery → Build → Roll-out",
    stack: ["TypeScript", "Next.js", "Postgres", "Keycloak", "AWS S3", "OpenAPI"],
    relatedService: "web-platforms",
    problem: "Ein mittelständischer Versicherer wickelte Schadenmeldungen über ein altes Web-Formular ab. 60% der Anrufe im Service-Center waren Statusabfragen 'wann bekomme ich Geld?'. Dokumente kamen per E-Mail oder Post. Die Kollegen tippten Schadenmeldungen ab.",
    solution: "Ein neues Selfservice-Portal mit drei Hauptfunktionen: Schaden melden (mit geführtem Dialog, Foto-Upload), Status verfolgen (jede Bearbeitung sichtbar, mit Zeitstempel und Verantwortlichem), Dokumente verwalten (Hochladen, Herunterladen, Signatur). Im Hintergrund: saubere API zwischen Portal und Schadensystem. Bestehende Schadenbearbeitenden mussten ihre Arbeitsweise nicht ändern.",
    workflow: [
      { icon: "▤", t: "Schaden", d: "Geführter Dialog" },
      { icon: "▦", t: "Upload", d: "Fotos + Belege" },
      { icon: "⟲", t: "ERP-Sync", d: "Schadensystem" },
      { icon: "▢", t: "Status", d: "Live-Verfolgung" },
      { icon: "✉", t: "Notify", d: "Bei jeder Änderung" },
    ],
    components: [
      "Kundenportal mit responsivem Design",
      "Keycloak-basiertes Login mit 2FA",
      "Geführter Schaden-Dialog mit Foto-Upload",
      "Bi-direktionale Synchronisation mit Schadensystem",
      "E-Mail-Notifications bei Status-Änderungen",
      "Admin-Backend für Kunden-Service",
      "Barrierefreiheit nach WCAG 2.1 AA",
    ],
    result: "Anteil der Schadenmeldungen über das Portal stieg von 12% auf 71% innerhalb von 6 Monaten. Anrufe im Service-Center sanken um 44%. Durchschnittliche Bearbeitungszeit pro Schaden sank von 11 auf 6 Werktage. NPS unter Online-Nutzern stieg um 28 Punkte.",
    metrics: [
      { val: "+59pp", lab: "Online-Schadenmeldungen", note: "12% → 71%" },
      { val: "−44%", lab: "Service-Center-Anrufe", note: "über 6 Monate" },
      { val: "−45%", lab: "Bearbeitungszeit", note: "11d → 6d" },
      { val: "+28", lab: "NPS Online-Nutzer", note: "über 6 Monate" },
    ],
    vizKind: "portal",
  },
  {
    slug: "document-processing",
    tag: "B2B · 2025",
    title: "Dokumenten-Verarbeitung mit OCR und Validierung",
    short: "2.000 Rechnungen pro Monat — von PDF-Anhang zu DATEV-Buchung, mit menschlicher Freigabe.",
    industry: "Mittelstand / Finanzbuchhaltung",
    duration: "8 Wochen",
    role: "Discovery → Build → Live",
    stack: ["TypeScript", "Node.js", "Postgres", "AWS Textract", "OpenAI", "DATEV API"],
    relatedService: "ai-automation",
    problem: "Die Buchhaltung verarbeitete monatlich 2.000 Eingangsrechnungen — alle als PDF. Eine Mitarbeiterin tippte Beträge, Kostenstellen, USt-Sätze manuell ab. Fehlerquote bei Tippen lag bei rund 4%. Genehmigungen liefen per E-Mail, was niemand mehr nachvollziehen konnte.",
    solution: "Eingangsrechnungen werden per E-Mail-Inbox an eine Pipeline weitergeleitet. OCR extrahiert Rohdaten, ein LLM normalisiert sie auf das DATEV-Schema (Konto, Kostenstelle, USt-Satz, Skonto). Bei hoher Konfidenz: automatischer Buchungsvorschlag. Bei niedriger: menschliche Freigabe mit Side-by-Side-Ansicht. Genehmigungs-Workflow ist im System.",
    workflow: [
      { icon: "✉", t: "Mail-In", d: "PDF-Eingang" },
      { icon: "⤳", t: "OCR", d: "Rohdaten" },
      { icon: "⊕", t: "Normalisierung", d: "LLM + Regeln" },
      { icon: "✓", t: "Freigabe", d: "Mensch wenn nötig" },
      { icon: "→", t: "DATEV", d: "Buchung" },
    ],
    components: [
      "E-Mail-Inbox-Listener mit Anhang-Erkennung",
      "OCR-Pipeline (AWS Textract)",
      "LLM-Normalisierung mit Confidence-Score",
      "Validierungs-UI mit Side-by-Side-Ansicht",
      "Genehmigungs-Workflow mit Vier-Augen-Prinzip",
      "DATEV-Integration mit OAuth-Anbindung",
      "Audit-Trail jeder Bearbeitung",
    ],
    result: "92% der Rechnungen werden automatisch verbucht. Manuelle Bearbeitungszeit pro Rechnung sank von 4 Minuten auf 18 Sekunden im Schnitt. Fehlerquote bei Buchungen sank von 4% auf unter 0,5%. Genehmigungen sind vollständig nachvollziehbar.",
    metrics: [
      { val: "92%", lab: "Automatisierungsgrad", note: "Auto-Buchung" },
      { val: "−93%", lab: "Bearbeitungszeit", note: "4min → 18s ⌀" },
      { val: "−87%", lab: "Fehlerquote", note: "4% → 0,5%" },
      { val: "2.000/Mo", lab: "Rechnungen verarbeitet", note: "0 manuelles Tippen" },
    ],
    vizKind: "ocr",
  },
  {
    slug: "saas-booking-platform",
    tag: "SaaS · 2025",
    title: "SaaS-Buchungsplattform für Dienstleister",
    short: "Multi-Tenant-Booking-Plattform mit Zahlungsabwicklung, Kalender-Sync und White-Label.",
    industry: "SaaS / Dienstleistung",
    duration: "20 Wochen",
    role: "Architektur → MVP → Skalierung",
    stack: ["TypeScript", "Next.js", "Postgres", "Stripe", "Redis", "BullMQ"],
    relatedService: "custom-software",
    problem: "Ein Gründer-Team hatte eine MVP-Buchungsplattform mit 12 zahlenden Kunden — aber das System brach bei jedem neuen Tenant zusammen. Kalender-Sync war fehleranfällig, Stripe-Abrechnung wurde manuell gemacht, White-Labeling unmöglich.",
    solution: "Wir bauten die Plattform neu auf: Multi-Tenant-Architektur mit isolierten Schemas, Stripe-Connect für transparente Auszahlungen an Dienstleister, robuste Kalender-Sync (Google + Outlook + Apple) mit Konflikt-Erkennung, vollständiges White-Labeling auf eigener Domain. MVP-Daten wurden ohne Downtime migriert.",
    workflow: [
      { icon: "★", t: "Kunde", d: "Bucht Termin" },
      { icon: "$", t: "Stripe", d: "Zahlung + Connect" },
      { icon: "▤", t: "Kalender", d: "Google/Outlook" },
      { icon: "✉", t: "Notify", d: "Beide Seiten" },
      { icon: "▣", t: "Dashboard", d: "Tenant-Sicht" },
    ],
    components: [
      "Multi-Tenant-Postgres mit Row-Level-Security",
      "Stripe Connect für Marketplace-Auszahlungen",
      "Kalender-Sync mit Two-Way-Webhooks",
      "White-Label-Konfiguration pro Tenant",
      "Buchungs-Widget zum Einbetten",
      "Admin-Backend für Plattform-Betreiber",
      "Background-Jobs für Reminder und Abrechnungen",
    ],
    result: "Plattform skaliert heute auf 240 zahlende Tenants ohne Performance-Probleme. Kalender-Konflikte (vorher Hauptbeschwerde) treten praktisch nicht mehr auf. ARR wuchs in 9 Monaten von 14k€ auf 290k€. Gründer-Team verbringt heute Zeit mit Wachstum statt mit Notfällen.",
    metrics: [
      { val: "12 → 240", lab: "Aktive Tenants", note: "über 9 Monate" },
      { val: "20×", lab: "Wachstum ARR", note: "14k → 290k €" },
      { val: "0,2%", lab: "Kalender-Konflikt-Rate", note: "vorher: 8%" },
      { val: "99.97%", lab: "Uptime SLA", note: "letzte 6 Monate" },
    ],
    vizKind: "saas",
  },
];

const LUCENT_PROCESS = [
  {
    n: "01",
    slug: "discovery",
    t: "Discovery",
    time: "1–2 Wochen",
    desc: "Wir tauchen tief in eure Codebasis, eure Nutzer:innen, eure Daten ein. Endet mit einer These, über die man streiten kann — keine Folien-Show.",
    deliverables: ["Stakeholder-Interviews (5–8)", "Codebase- und Daten-Audit", "Tech-Risk-Register", "Aktivität-Map des Status-Quo"],
    decision: "Welche Hypothese wollen wir mit dem Prototyp beweisen oder widerlegen?",
    example: "Bei der Lead-Qualifizierung haben wir 200 historische Anfragen manuell durchgesehen, um zu verstehen, was 'Tier-A' wirklich heißt — bevor wir eine Zeile Code geschrieben haben.",
  },
  {
    n: "02",
    slug: "system-mapping",
    t: "System-Mapping",
    time: "1 Woche",
    desc: "Wir zeichnen das technische Zielbild: Datenflüsse, Integrationen, Verantwortungen. Im Diagramm streiten ist billig — im Code teuer.",
    deliverables: ["C4-Diagramme (System, Container, Component)", "Daten-Wörterbuch", "API-Spec-Skizze (OpenAPI)", "Tech-Stack-Empfehlung mit Trade-offs"],
    decision: "Auf welcher Architektur und welchen Schnittstellen wollen wir aufbauen?",
    example: "Beim Logistik-Dashboard hatten wir nach zwei Tagen ein Datenfluss-Diagramm an der Wand. Drei Annahmen waren falsch — wir haben sie korrigiert, bevor jemand Code geschrieben hat.",
  },
  {
    n: "03",
    slug: "ux-prototype",
    t: "UX/UI-Prototyp",
    time: "2–3 Wochen",
    desc: "Klickbarer Prototyp mit echten Daten, getestet mit echten Nutzer:innen. Das Kleinste, das die Wette beweist — nicht das Vollständigste.",
    deliverables: ["Klickbarer Prototyp (Figma + Code)", "User-Tests mit 5+ Personen", "Design-System-Skizze", "Akzeptanz-Kriterien für MVP"],
    decision: "Geht der Prototyp in den vollen Build, oder müssen wir das Konzept anpassen?",
    example: "Beim Versicherungs-Portal haben wir den Prototyp mit echten Versicherten getestet. Drei Schritte im Schadenmelder waren so verwirrend, dass wir den ganzen Flow umgebaut haben — vor dem Bauen.",
  },
  {
    n: "04",
    slug: "development",
    t: "Development",
    time: "6–16 Wochen",
    desc: "Wöchentliche Demos auf eurer Staging-Umgebung. Trunk-based-Development, Feature-Flags, Tests von Tag eins. Was wir zeigen, läuft.",
    deliverables: ["Funktionierende Anwendung in Staging", "Wöchentliche Demos und Sprint-Notes", "Test-Coverage und CI/CD-Pipeline", "Technische Dokumentation"],
    decision: "Welche Features schaffen es in den MVP, welche in Phase 2?",
    example: "Beim Booking-SaaS haben wir nach 4 Wochen einen MVP gezeigt — mit dem die Gründer schon die ersten 3 neuen Tenants onboarden konnten, während wir parallel an Phase 2 gebaut haben.",
  },
  {
    n: "05",
    slug: "testing",
    t: "Testing & Iteration",
    time: "2–4 Wochen",
    desc: "Automatisierte Tests, Last-Tests, Security-Audit. Echte Pilot-Nutzer:innen, echtes Feedback, echte Bugs — alles vor dem Launch.",
    deliverables: ["E2E- und Last-Test-Suite", "Security-Audit-Report", "Pilot-Phase mit Feedback-Schleife", "Bug- und UX-Iteration"],
    decision: "Sind wir bereit für den vollen Launch — oder brauchen wir noch eine Runde?",
    example: "Beim Dokumenten-OCR haben wir die ersten 100 Rechnungen durch beide Pipelines laufen lassen — manuell UND automatisch — und Abweichungen ausgewertet. Die Confidence-Schwellen wurden danach feingetunt.",
  },
  {
    n: "06",
    slug: "launch",
    t: "Launch",
    time: "1–2 Wochen",
    desc: "Gestaffelter Roll-out mit Feature-Flags. 10% → 50% → 100%. Bei Problemen rollback in Sekunden, nicht in Tagen.",
    deliverables: ["Produktions-Deployment mit Canary-Roll-out", "Monitoring und Alerts live", "Roll-out-Playbook und Rollback-Plan", "Launch-Kommunikation an Stakeholder"],
    decision: "Wer übernimmt nach dem Launch den Betrieb — euer Team, unser Team, oder gemeinsam?",
    example: "Beim Logistik-Dashboard haben wir mit einer Filiale gestartet, dann nach 2 Wochen auf alle ausgeweitet. Eine kritische Race-Condition kam zum Vorschein — durch den gestaffelten Roll-out aber ohne Ausfall.",
  },
  {
    n: "07",
    slug: "support",
    t: "Support & Skalierung",
    time: "laufend",
    desc: "Übergabe mit Runbooks, Dashboards, Pager-Rotation — oder wir bleiben dran. Eure Wahl. Bei Skalierungsfragen oder neuen Features melden wir uns sofort.",
    deliverables: ["Runbooks für häufige Vorfälle", "Monitoring-Dashboard mit SLOs", "Pager-Rotation oder Support-SLA", "Quartals-Reviews mit Roadmap-Vorschlag"],
    decision: "Welches Support-Modell passt für eure Organisation?",
    example: "Beim Lead-Qualifizierungs-System fahren wir seit 14 Monaten On-Call. Im Durchschnitt 0,3 Incidents pro Monat, mittlere Lösungszeit unter 45 Minuten.",
  },
];

const LUCENT_FAQS = [
  {
    q: "Wie unterscheidet ihr euch von einer klassischen Agentur?",
    a: "Wir sind kein Versorger und keine Body-Leasing-Bude. Wir sind ein kleines Senior-Team, das Software-Produkte verantwortet — mit Architektur-Entscheidungen, Code-Reviews, Demo-Tagen und Übergabe-Konzept. Wenn ihr fünf Junior-Entwickler:innen für ein Festpreis-Pflichtenheft sucht, sind wir falsch. Wenn ihr ein Tool baut, das jemand pflegen muss, sind wir richtig.",
  },
  {
    q: "Was kostet ein typisches Projekt?",
    a: "Custom-Software-Projekte starten in der Regel bei 35.000 € (8–12 Wochen, MVP-Scope) und gehen bis 250.000 €+ für vollständige Plattformen. Wir arbeiten zu Wochen- oder Sprint-Sätzen, nicht zu Festpreisen — weil Festpreise bedeuten, dass jemand auf der falschen Seite einer Kalkulation sitzt. Transparente Schätzung nach dem ersten Gespräch.",
  },
  {
    q: "Wie lange dauert ein Projekt?",
    a: "Discovery: 1–2 Wochen. Prototyp: 2–3 Wochen. Vollständiges Build: 6–16 Wochen. Wir machen keine 18-Monats-Wasserfälle. Wenn etwas länger dauern muss, brechen wir es in Phasen mit klaren Lieferterminen.",
  },
  {
    q: "Bekommen wir den Code? Können wir das Projekt selbst weiterführen?",
    a: "Ja. Repository in eurer Organisation, vollständige Dokumentation, Onboarding-Sessions für euer Team. Wir bauen so, dass das nachfolgende Team unseren Code gerne übernimmt. Kein Lock-in, keine versteckten Lizenzen, kein Hostspezifisches Hexenwerk.",
  },
  {
    q: "Arbeitet ihr mit unserem bestehenden Team?",
    a: "Ja, das ist oft der Idealfall. Wir können als verlängerte Werkbank arbeiten (mit Daily-Sync ins Team), als unabhängiges Squad mit eigener Verantwortung oder als Mentoren für euer Team. Pairing-Sessions und Code-Reviews mit euren Entwickler:innen sind Standard.",
  },
  {
    q: "Was, wenn wir noch gar kein klares Konzept haben?",
    a: "Dann startet ihr genau richtig. Unser Discovery-Modul ist dafür da: in 1–2 Wochen kommen wir mit euch zu einer These, die wir mit einem Prototyp testen können. Wenn am Ende rauskommt, dass ihr keine Software, sondern einen Prozess-Change braucht, sagen wir das auch.",
  },
  {
    q: "Wo seid ihr ansässig? Müssen wir nach Ulm kommen?",
    a: "Wir sitzen in Ulm und arbeiten in der Regel remote, mit regelmäßigen Vor-Ort-Tagen bei euch oder bei uns. Discovery-Workshop und Demo-Tage gerne live, das tägliche Bauen über Slack und Linear. Bisher hat noch niemand wegen Distanz unter dem Ergebnis gelitten.",
  },
  {
    q: "Wie steht es um Datenschutz und Compliance?",
    a: "Wir arbeiten DSGVO-konform und mit DPA. Für regulierte Branchen (Fintech, Health, Public) haben wir Erfahrung mit ISO 27001, BaFin-Anforderungen, HL7/FHIR und DSGVO-konformen KI-Workflows. Daten bleiben — wo es geht — in EU-Regionen, KI-Anbieter werden danach ausgewählt.",
  },
];

const LUCENT_INDUSTRIES = [
  { i: "{ }", t: "SaaS & Startups", d: "Von der Pre-Seed-MVP bis zur Series-B-Skalierung.", l: "Startup · Scale-up" },
  { i: "$", t: "Fintech", d: "Compliance-fähige Plattformen, Zahlungsabwicklung, Reporting.", l: "BaFin · PSD2 · ISO 27001" },
  { i: "▣", t: "E-Commerce", d: "Headless-Setups, Custom Storefronts, B2B-Portale.", l: "Headless · D2C · B2B" },
  { i: "⚙", t: "Industrie & B2B", d: "MES, IIoT, interne Tools für Produktion und Vertrieb.", l: "Mittelstand · Industrie 4.0" },
  { i: "♡", t: "Health & MedTech", d: "Datenschutzkonforme Lösungen für Versorger und Anbieter.", l: "DSGVO · HL7 · MDR" },
  { i: "⬢", t: "Logistik", d: "Tracking, Routing, ERP-Anbindungen mit echter Wirkung.", l: "TMS · WMS · OMS" },
  { i: "✦", t: "Bildung & Public", d: "Plattformen für Schulen, Behörden, gemeinnützige Träger.", l: "Public · NGO" },
  { i: "+", t: "Andere?", d: "Jede Branche, in der Software ein Hebel ist. Erzählt uns davon.", l: "Erstgespräch · 30 min" },
];

const LUCENT_NAV = [
  { href: "leistungen.html", label: "Leistungen", key: "leistungen" },
  { href: "cases.html", label: "Cases", key: "cases" },
  { href: "process.html", label: "Prozess", key: "process" },
  { href: "about.html", label: "Über uns", key: "about" },
];

Object.assign(window, {
  LUCENT_SERVICES,
  LUCENT_CASES,
  LUCENT_PROCESS,
  LUCENT_FAQS,
  LUCENT_INDUSTRIES,
  LUCENT_NAV,
});
